### PR TITLE
Upgraded fading_edge_scrollview to ^4.0.0. Fixes #95

### LINKED ISSUE #95: error build for flutter 3.22.0
```dart
Could not build the precompiled application for the device.
Error (Xcode): ../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
```

### PR DESCRIPTION
**Pull request by bkleineibst**
# Fixes build for flutter 3.22.0.

Upgraded to ^4.0.0 of fading_edge_scrollview.

# Related items

Fixes #95

### CODE REVIEW

**Review by hatim-essadeq — APPROVED** [review]

**Comment by hasanm08** [comment]
can you send it to pub please?

**Review by gunantosteven — APPROVED** [review]

**Comment by Rodrigo-Youse** [comment]
@MarcelGarus You know when the new version using this pr is released?

**Comment by Rodrigo-Youse** [comment]
@bkleineibst the fading_edge_scrollview have a new version released a 3 months

fading_edge_scrollview: ^4.1.1

What do you think to update this pull request?

**Comment by bkleineibst** [comment]
@Rodrigo-Youse Increased to 4.1.0 as this is the lowest version that will work in flutter 3.22.0

**Comment by realitymolder** [comment]
done!

**Pull request closed without merging**
