### PR TITLE
Updates to dependencies

### PR DESCRIPTION
**Pull request by Attempt3035**
Widened dependency ranges for SDK and fading_edge_scrollview

### CODE REVIEW

**Comment by Attempt3035** [comment]
Hey @MarcelGarus! Just wondering if you're still maintaining this package, I use it a lot and would be keen to help out if needed!

**Comment by sixtusagbo** [comment]
Hey maintainers (@MarcelGarus), please merge this PR so that we can use this package. There's a null error in the old version of fading_edge_scrollview which you're currectly using and it's causing a build failure.

```
/C:/Users/.../Pub/Cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
 - 'PageController' is from 'package:flutter/src/widgets/page_view.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/page_view.dart').
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
      scrollController: child.controller,
                              ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

**Comment by sixtusagbo** [comment]
Since maintainers are reluctant to merge this, I decided to try implementing it without a package: https://gist.github.com/sixtusagbo/3f905c7b774057e32ee5485ec97c15d2
@Attempt3035 or anyone who comes across this can use it.

**Comment by Attempt3035** [comment]
That's awesome, thank you @sixtusagbo !

**Comment by realitymolder** [comment]
done!

**Pull request closed without merging**
